import {
    MdDashboard,
    MdTour,
    MdContactPhone,
    MdTrendingUp,
    MdOnlinePrediction,
    MdDoNotDisturbOnTotalSilence,
    MdTrendingDown,
    MdOutlineAttachFile,
    MdBlock,
    MdDelete,
} from "react-icons/md";
import { IoMdAnalytics, IoIosCreate, IoIosSettings, IoIosSunny, IoIosMoon, IoMdCreate, IoIosAdd } from "react-icons/io";
import { HiDocumentReport } from "react-icons/hi";
import { GrUserAdmin } from "react-icons/gr";
import {
    FaUserAlt,
    FaClipboardList,
    FaChevronDown,
    FaChevronUp,
    FaChevronLeft,
    FaSearch,
    FaUsers,
    FaBell,
    FaMap,
    FaMapMarkedAlt,
    FaFire,
    FaRocket,
    FaChartBar,
    FaEye,
    FaEyeSlash,
} from "react-icons/fa";
import { BiSolidChevronsRight } from "react-icons/bi";
import { TbBrandBooking } from "react-icons/tb";
import { GoPackage } from "react-icons/go";
const icons = {
    MdDashboard,
    IoMdAnalytics,
    HiDocumentReport,
    GrUserAdmin,
    FaUserAlt,
    MdTour,
    IoIosCreate,
    FaClipboardList,
    TbBrandBooking,
    MdContactPhone,
    IoIosSettings,
    FaChevronDown,
    FaChevronUp,
    FaChevronLeft,
    FaSearch,
    GoPackage,
    MdTrendingUp,
    MdOnlinePrediction,
    MdDoNotDisturbOnTotalSilence,
    FaUsers,
    IoIosMoon,
    IoIosSunny,
    FaBell,
    FaMap,
    FaMapMarkedAlt,
    FaFire,
    FaRocket,
    FaChartBar,
    MdTrendingDown,
    FaEye,
    FaEyeSlash,
    MdOutlineAttachFile,
    MdBlock,
    MdDelete,
    IoMdCreate,
    IoIosAdd,
    BiSolidChevronsRight,
};
export default icons;
