import {
    MdDashboard,
    MdTour,
    MdContactPhone,
    MdTrendingUp,
    MdOnlinePrediction,
    MdDoNotDisturbOnTotalSilence,
    MdTrendingDown,
    MdOutlineAttachFile,
    MdBlock,
    MdDelete,
    MdEmail,
    MdPayment,
    MdCheckCircle,
    MdContactSupport,
} from "react-icons/md";
import {
    IoMdAnalytics,
    IoIosCreate,
    IoIosSettings,
    IoIosSunny,
    IoIosMoon,
    IoMdCreate,
    IoIosAdd,
    IoIosArrowDropdownCircle,
    IoIosUnlock,
    IoIosLock,
} from "react-icons/io";
import { HiDocumentReport } from "react-icons/hi";
import { FiLogOut } from "react-icons/fi";
import { GrUserAdmin } from "react-icons/gr";
import {
    FaUserAlt,
    FaClipboardList,
    FaChevronDown,
    FaChevronUp,
    FaChevronLeft,
    FaSearch,
    FaUsers,
    FaBell,
    FaMap,
    FaMapMarkedAlt,
    FaFire,
    FaRocket,
    FaChartBar,
    FaEye,
    FaEyeSlash,
    FaCopy,
    FaFileExcel,
    FaFilePdf,
    FaPrint,
    FaFileCsv,
} from "react-icons/fa";
import { RiLockPasswordFill } from "react-icons/ri";
import { BiSolidChevronsRight } from "react-icons/bi";
import { TbBrandBooking } from "react-icons/tb";
import { GoPackage } from "react-icons/go";

const icons = {
    MdDashboard,
    IoMdAnalytics,
    HiDocumentReport,
    GrUserAdmin,
    FaUserAlt,
    MdTour,
    IoIosCreate,
    FaClipboardList,
    TbBrandBooking,
    MdContactPhone,
    IoIosSettings,
    FaChevronDown,
    FaChevronUp,
    FaChevronLeft,
    FaSearch,
    GoPackage,
    MdTrendingUp,
    MdOnlinePrediction,
    MdDoNotDisturbOnTotalSilence,
    FaUsers,
    IoIosMoon,
    IoIosSunny,
    FaBell,
    FaMap,
    FaMapMarkedAlt,
    FaFire,
    FaRocket,
    FaChartBar,
    MdTrendingDown,
    FaEye,
    FaEyeSlash,
    MdOutlineAttachFile,
    MdBlock,
    MdDelete,
    IoMdCreate,
    IoIosAdd,
    BiSolidChevronsRight,
    FaCopy,
    FaFileExcel,
    FaFilePdf,
    FaPrint,
    FaFileCsv,
    IoIosArrowDropdownCircle,
    RiLockPasswordFill,
    FiLogOut,
    MdEmail,
    MdPayment,
    MdCheckCircle,
    IoIosUnlock,
    IoIosLock,
    MdContactSupport,
};
export default icons;
